version: '24.0'

services :
#Eureka
  eurekaServer : 
    build : ./EurekaServer/Eureka
    ports : 
      - "8761:8761"
    image : "eureka"

#product-Microservice
  productmicroservice : 
    build : ./ProductMicroservice/Product
    ports : 
      - "8701:3308"
    image : "productmicroservice"
    depends_on : 
      - eurekaServer
    environment :
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
#Pari-Microservice
  parimicroservice :
    build : ./PariMicroService
    ports :
      - "8766:8086"
    image : "parimicroservice"
    depends_on :
      - eurekaServer
    environment :
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/

#user-Microservice
  msuser : 
    build : ./MsUser
    ports : 
      - "8799:3309"
    image : "msuser"
    depends_on : 
      - eurekaServer
    environment :
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/   
#Auction-Microservice
  auctionmicroservice :
    build : ./Auction
    ports :
      - "8702:3000"
    image : "auctionmicroservice"
    depends_on :
      - eurekaServer
    environment :
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/

#commande-Microservice
  commandemicroservice : 
    build : ./produit
    ports : 
      - "8708:3315"
    image : "commandemicroservice"
    depends_on :
      - eurekaServer
    environment :
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
      
  #Enchere-Microservice
  #enchermicroservice :
    #build : ./Enchere
    #ports :
    #  - "8801:8087"
    #image : "encheremicroservice"
    #depends_on :
    #  - eurekaServer
    #environment :
    #  - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/

#Gateway-Microservice
  gateway : 
    build : ./API_Gateway_Server
    ports : 
      - "8798:3310"
    image : "gateway"
    depends_on :
      - eurekaServer
    environment :
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
