version: '24.0.6'

services :
#Eureka
  eurekaServer : 
    build : ./EurekaServer/Eureka
    ports : 
      - "8761:8761"
    image : "eureka"

#User-Microservice
  usermicroservice : 
    build : ./userMicroservice
    ports : 
      - "8700:8058"
    image : "usermicroservice"
    depends_on : 
      - eurekaServer
    environment :
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/